[20240530 13:36:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:38 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:38 save_data.py:20 INFO]: Linking DB error
[20240530 13:36:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:43 save_data.py:20 INFO]: Linking DB error
[20240530 13:36:45 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:47 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:47 save_data.py:20 INFO]: Linking DB error
[20240530 13:36:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:52 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:52 save_data.py:20 INFO]: Linking DB error
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: Input request body error
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:36:54 save_data.py:20 INFO]: Created the create_huan_jia_table data
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: Input request body error
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:54 save_data.py:20 INFO]: Input request body error
[20240530 13:36:55 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:55 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:36:55 save_data.py:20 INFO]: Input request body error
[20240530 13:37:02 save_data.py:20 INFO]: The repair_table already exists.
[20240530 13:37:02 save_data.py:20 INFO]: The machine_table already exists.
[20240530 13:37:02 save_data.py:20 INFO]: The part_table already exists.
[20240530 13:37:02 save_data.py:20 INFO]: The part_statistic_table already exists.
[20240530 13:37:02 save_data.py:20 INFO]: The machine_state_table already exists.
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: Input request body error
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: Input request body error
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: Input request body error
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:02 save_data.py:20 INFO]: Input request body error
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the repair_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the machine_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the part_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the part_statistic_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the machine_state_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:29 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:29 save_data.py:20 INFO]: Created the create_huan_jia_table data
[20240530 13:37:29 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:30 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:30 save_data.py:20 INFO]: Created the create_part_list data
[20240530 13:37:30 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:30 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:30 save_data.py:20 INFO]: Created the create_device_table data
[20240530 13:37:30 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 13:37:30 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:37:30 save_data.py:20 INFO]: Created the create_machine_list data
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:39 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:39 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:40 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:40 save_data.py:20 INFO]: Created the part_list table
[20240530 13:39:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:39:40 save_data.py:20 INFO]: Created the part_list table
[20240530 13:41:36 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:41:36 save_data.py:20 INFO]: Created the part_list table
[20240530 13:47:21 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:47:21 save_data.py:20 INFO]: Created the repair table
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:56 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created the machine name and device id
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 13:48:57 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:05:46 save_data.py:20 INFO]: [Error] Input request body error; C:\Users\jimlee\Desktop\test backend\backend\save_data.py. link_Postgres at line 51.
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:40 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:40 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created table or insert data successfully
[20240530 14:06:41 save_data.py:20 INFO]: Created the machine name and device id
